# config/packages/nelmio_api_doc.yaml
nelmio_api_doc:
    documentation:
        info:
            title: 'API de mon projet'
            description: 'Documentation de l’API'
            version: '1.0.0'
    areas: # Facultatif : utile si vous voulez limiter les routes documentées
        default:
            path_patterns: [ '^/api' ]
